config/routes.rb
Eforo::Application.routes.draw do

  get "home/index"
  post "home/votar"
  get "home/estado"
  get "home/pregunta"
  get "home/estadisticas"
  get "home/acercade"
  get "home/licenciamiento"

  namespace :admin do
    resources :candidatos do
      member do
        get 'reorder'
      end
    end
    resources :eventos do
      member do
        get 'reset'
      end
    end
    resources :preguntas
    resource :dashboard do
      collection do
        get 'siguiente_pregunta'
        get 'siguiente_candidato'
      end
    end
  end

  match 'dashboard' => "admin/dashboard#show", :as => :dashboard
  match 'estadisticas' => "home#estadisticas", :as => :estadisticas
  match 'acercade' => "home#acercade", :as => :acercade
  match 'licenciamiento' => "home#licenciamiento", :as => :licenciamiento

  root :to => "home#index"

end

app/models/pregunta.rb
class Pregunta
  include MongoMapper::Document

  key :orden, Integer
  key :texto, String

  validates_presence_of :orden, :texto

  def to_label
    orden.to_s + '. ' + texto
  end
end

app/controllers/admin/preguntas_controller.rb
# -*- coding: utf-8 -*-
class Admin::PreguntasController < ApplicationController
  before_filter :authenticate_htaccess
  layout 'admin'

  # access_control do
  #   allow :administrador
  # end

  def index


    q = params[:search].nil? ? '%' : '%'+params[:search][0]+'%'

    @preguntas = Pregunta.all(:order => "orden").paginate(:page    => params[:page])
    #    @preguntas = Pregunta.all(:order => "orden").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @preguntas }
    end
  end

  def show
    @pregunta = Pregunta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pregunta }
    end
  end

  def new
    @pregunta = Pregunta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pregunta }
    end
  end

  def edit
    @pregunta = Pregunta.find(params[:id])
  end

  def create
    @pregunta = Pregunta.new(params[:pregunta])

    if @pregunta.orden.nil?
      back_to_dashboard = true
      @pregunta.orden = Pregunta.last(:order => :orden).orden + 1
    else
      back_to_dashbard = false
    end

    respond_to do |format|
      if @pregunta.save
        flash[:notice] = 'Registro creado con éxito.'

        expire_action :controller => "/home", :action => :index
        expire_action :controller => "/home", :action => :estadisticas


        format.html {
          if back_to_dashboard == true
            Evento.set_pregunta(@pregunta.id)
            redirect_to dashboard_path
          else
            redirect_to(admin_pregunta_path(@pregunta))
          end
        }
        format.xml  { render :xml => @pregunta, :status => :created, :location => @pregunta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pregunta.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @pregunta = Pregunta.find(params[:id])

    respond_to do |format|
      if @pregunta.update_attributes(params[:pregunta])
        flash[:notice] = 'Registro actualizado con éxito.'

        expire_action :controller => "/home", :action => :index
        expire_action :controller => "/home", :action => :estadisticas



        format.html { redirect_to(admin_pregunta_path(@pregunta)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pregunta.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @pregunta = Pregunta.find(params[:id])
    @pregunta.destroy

    respond_to do |format|
      if @pregunta.destroy

        expire_action :controller => "/home", :action => :index
        expire_action :controller => "/home", :action => :estadisticas
        

        format.html { redirect_to(admin_preguntas_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "show"}
      end
    end
  end

end

app/views/admin/preguntas/_breadcrumbs.html.haml
#breadcrumbs
  %ul#crumbs
    %li
      = link_to 'Panel Control', admin_dashboard_path
    %li
      = link_to 'Preguntas', admin_preguntas_path
    - if @forview
      - if @forview == "NEW"
        %li= t("data.title_new")
      - elsif @forview == "EDIT"
        %li= t("data.title_edit")
      - else
        %li= t("data.title_show")
.clear &nbsp;

app/views/admin/preguntas/_form.html.haml
- form.inputs do
  = form.input :orden
  = form.input :texto, :as => :text

app/views/admin/preguntas/edit.html.haml
- @forview = "EDIT"
= render :partial=>"breadcrumbs"

.mantform
  %h2
    Editar 
    = Pregunta.model_name.human

  - semantic_form_for @pregunta, :url => admin_pregunta_path(@pregunta) do |form|
    = form.semantic_errors
    = render :partial => 'form', :locals => {:form => form}
    = buttons_update(admin_preguntas_path)

app/views/admin/preguntas/index.html.haml
= render :partial => "breadcrumbs"
.listing
  %h2= 'Preguntas'
  %div{:id => "options"}
    = button_new(new_admin_pregunta_path)
    = render :partial => 'shared/findbox', :locals => {:url => admin_preguntas_path}
  %table.minimalist-b
    %thead
      %tr
        %th= 'Orden'
        %th= 'Texto'
    %tbody
      - for pregunta in @preguntas
        %tr
          %td= pregunta.orden
          %td= link_to pregunta.texto, admin_pregunta_path(pregunta)
  = will_paginate @preguntas
  

app/views/admin/preguntas/new.html.haml
- @forview = "NEW"
= render :partial=>"breadcrumbs"

.mantform
  %h2
    Nuevo 
    = Pregunta.model_name.human

  - semantic_form_for @pregunta, :url => admin_preguntas_path do |form|
    = form.semantic_errors
    = render :partial => 'form', :locals => {:form => form}
    = buttons_create(admin_preguntas_path)

app/views/admin/preguntas/show.html.haml
- @forview = "SHOW"
= render :partial=>"breadcrumbs"

- if @pregunta.errors.any?
  .error
    %ul
    - @pregunta.errors.full_messages.each do |msg|
      %li= msg

.show
  %h2= Pregunta.model_name.human

  %div{:id=>"options"}
    = button_new(new_admin_pregunta_path)
    = button_edit(edit_admin_pregunta_path(@pregunta))
    = button_delete(admin_pregunta_path(@pregunta))
    = button_cancel(admin_preguntas_path)
    %br

  .box
    %table
      %colgroup.show-table-header
      %colgroup.show-table-data
      %tr
        %th= label :_id, Pregunta.human_attribute_name(:_id)
        %td= @pregunta._id
      %tr
        %th= label :orden, Pregunta.human_attribute_name(:orden)
        %td= @pregunta.orden
      %tr
        %th= label :texto, Pregunta.human_attribute_name(:texto)
        %td= @pregunta.texto