config/routes.rb
Eforo::Application.routes.draw do

  get "home/index"
  post "home/votar"
  get "home/estado"
  get "home/pregunta"
  get "home/estadisticas"
  get "home/acercade"
  get "home/licenciamiento"

  namespace :admin do
    resources :candidatos do
      member do
        get 'reorder'
      end
    end
    resources :eventos do
      member do
        get 'reset'
      end
    end
    resources :preguntas
    resource :dashboard do
      collection do
        get 'siguiente_pregunta'
        get 'siguiente_candidato'
      end
    end
  end

  match 'dashboard' => "admin/dashboard#show", :as => :dashboard
  match 'estadisticas' => "home#estadisticas", :as => :estadisticas
  match 'acercade' => "home#acercade", :as => :acercade
  match 'licenciamiento' => "home#licenciamiento", :as => :licenciamiento

  root :to => "home#index"

end

app/models/candidato.rb
class Candidato
  include MongoMapper::Document

  key :codigo, Integer
  key :nombre, String
  key :partido, String
  key :url, String
  key :slug, String
  key :imagen, String

  validates_presence_of :codigo, :nombre, :partido, :url, :imagen


  def to_label
    codigo.to_s + '. ' + nombre
  end
end

app/controllers/admin/candidatos_controller.rb
# -*- coding: utf-8 -*-
class Admin::CandidatosController < ApplicationController
  layout 'admin'

  before_filter :authenticate_htaccess

  def index
    @candidatos = Candidato.all(:order => "codigo")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @candidatos }
    end
  end

  def show
    @candidato = Candidato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @candidato }
    end
  end

  def new
    @candidato = Candidato.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @candidato }
    end
  end

  def edit
    @candidato = Candidato.find(params[:id])
  end

  def create
    @candidato = Candidato.new(params[:candidato])

    respond_to do |format|
      if @candidato.save
        flash[:notice] = 'Registro creado con éxito.'

        expire_action :controller => "/home", :action => :index
        expire_action :controller => "/home", :action => :estadisticas

        format.html { redirect_to(admin_candidato_path(@candidato)) }
        format.xml  { render :xml => @candidato, :status => :created, :location => @candidato }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @candidato.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @candidato = Candidato.find(params[:id])

    respond_to do |format|
      if @candidato.update_attributes(params[:candidato])
        flash[:notice] = 'Registro actualizado con éxito.'

        expire_action :controller => "/home", :action => :index
        expire_action :controller => "/home", :action => :estadisticas


        format.html { redirect_to(admin_candidato_path(@candidato)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @candidato.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @candidato = Candidato.find(params[:id])
    @candidato.destroy

    expire_action :controller => "/home", :action => :index
    expire_action :controller => "/home", :action => :estadisticas

    respond_to do |format|
      format.html { redirect_to(admin_candidatos_url) }
      format.xml  { head :ok }
    end
  end

  def reorder
    @candidato = Candidato.find(params[:id])

    codigo =  params[:codigo].to_i

    if codigo > 0
      old_candidato = Candidato.find_by_codigo(codigo)
      old_candidato.codigo = @candidato.codigo
      old_candidato.save

      @candidato.codigo = codigo
      @candidato.save
    end

    expire_action :controller => "/home", :action => :index
    expire_action :controller => "/home", :action => :estadisticas

    redirect_to admin_candidatos_url
  end

end

app/helpers/admin/candidatos_helper.rb
module Admin::CandidatosHelper
end

app/views/admin/candidatos/_breadcrumbs.html.haml
#breadcrumbs
  %ul#crumbs
    %li
      = link_to 'Panel Control', admin_dashboard_path
    %li
      = link_to Candidato.human_name.pluralize, admin_candidatos_path
    - if @forview
      - if @forview == "NEW"
        %li= t("data.title_new")
      - elsif @forview == "EDIT"
        %li= t("data.title_edit")
      - else
        %li= t("data.title_show")
.clear &nbsp;

app/views/admin/candidatos/_form.html.haml
- form.inputs do
  = form.input :codigo
  = form.input :nombre
  = form.input :partido
  = form.input :url
  = form.input :slug
  = form.input :imagen

app/views/admin/candidatos/edit.html.haml
- @forview = "EDIT"
= render :partial=>"breadcrumbs"

.mantform
  %h2
    Editar 
    = Candidato.human_name

  - semantic_form_for @candidato, :url => admin_candidato_path(@cantidato) do |form|
    = form.semantic_errors
    = render :partial => 'form', :locals => {:form => form}
    = buttons_update(admin_candidatos_path)

app/views/admin/candidatos/index.html.haml
= render :partial => "breadcrumbs"
.listing
  %h2= Candidato.human_name.pluralize
  %div{:id => "options"}
    = button_new(new_admin_candidato_path)
    =# render :partial => 'shared/findbox', :locals => {:url => admin_candidatos_path}
  %table.minimalist-b
    %thead
      %tr
        %th= 'Orden'
        %th= Candidato.human_attribute_name(:nombre)
        %th{:colspan => 2}= "Ordenar"
    %tbody
      - for candidato in @candidatos
        %tr
          %td= candidato.codigo
          %td= link_to candidato.nombre, admin_candidato_path(candidato)
          %td= link_to(image_tag('blue_up.png'), reorder_admin_candidato_path(candidato, :codigo => (candidato.codigo - 1) ) ) unless (candidato.codigo - 1 ) == 0
          %td= link_to image_tag('blue_down.png'), reorder_admin_candidato_path(candidato, :codigo => (candidato.codigo + 1) ) 
  =# will_paginate @candidatos
  

app/views/admin/candidatos/new.html.haml
- @forview = "NEW"
= render :partial=>"breadcrumbs"

.mantform
  %h2
    Nuevo 
    = Candidato.human_name

  - semantic_form_for @candidato, :url => admin_candidatos_path do |form|
    = form.semantic_errors
    = render :partial => 'form', :locals => {:form => form}
    = buttons_create(admin_candidatos_path)

app/views/admin/candidatos/show.html.haml
- @forview = "SHOW"
= render :partial=>"breadcrumbs"

- if @candidato.errors.any?
  .error
    %ul
    - @candidato.errors.full_messages.each do |msg|
      %li= msg

.show
  %h2= Candidato.human_name

  %div{:id=>"options"}
    = button_new(new_admin_candidato_path)
    = button_edit(edit_admin_candidato_path(@candidato))
    = button_delete(admin_candidato_path(@candidato))
    = button_cancel(admin_candidatos_path)
    %br

  .box
    %table
      %colgroup.show-table-header
      %colgroup.show-table-data
      %tr
        %th= label :_id, Candidato.human_attribute_name(:_id)
        %td= @candidato._id
      %tr
        %th= label :codigo, Candidato.human_attribute_name(:codigo)
        %td= @candidato.codigo
      %tr
        %th= label :nombre, Candidato.human_attribute_name(:nombre)
        %td= @candidato.nombre
      %tr
        %th= label :partido, Candidato.human_attribute_name(:partido)
        %td= @candidato.partido
      %tr
        %th= label :url, Candidato.human_attribute_name(:url)
        %td= @candidato.url
      %tr
        %th= label :slug, Candidato.human_attribute_name(:slug)
        %td= @candidato.slug