config/routes.rb
Eforo::Application.routes.draw do

  get "home/index"
  post "home/votar"
  get "home/estado"
  get "home/pregunta"
  get "home/estadisticas"
  get "home/acercade"
  get "home/licenciamiento"

  namespace :admin do
    resources :candidatos do
      member do
        get 'reorder'
      end
    end
    resources :eventos do
      member do
        get 'reset'
      end
    end
    resources :preguntas
    resource :dashboard do
      collection do
        get 'siguiente_pregunta'
        get 'siguiente_candidato'
      end
    end
  end

  match 'dashboard' => "admin/dashboard#show", :as => :dashboard
  match 'estadisticas' => "home#estadisticas", :as => :estadisticas
  match 'acercade' => "home#acercade", :as => :acercade
  match 'licenciamiento' => "home#licenciamiento", :as => :licenciamiento

  root :to => "home#index"

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  before_filter :authenticate_htaccess

  def show
    @evento = Evento.last
    @preguntas = Pregunta.all(:order => "orden")
    @candidatos = Candidato.all(:order => "codigo")
    @pregunta = Pregunta.new
  end

  def siguiente_pregunta
    Evento.siguiente_pregunta
    expire_action :controller => '/home', :action => 'index'
    expire_action :controller => '/home', :action => "estadisticas"
    redirect_to(admin_dashboard_path)
  end

  def siguiente_candidato
    unless Evento.siguiente_candidato
      Evento.siguiente_pregunta(false)
    end
    expire_action :controller => '/home', :action => 'index'
    expire_action :controller => '/home', :action => "estadisticas"
    redirect_to(admin_dashboard_path)
  end

end

app/views/admin/dashboard/show.html.haml
%h1 Panel de Control

= link_to 'Candidatos', admin_candidatos_path, :title => "Administrar listado de candidatos", :class => 'button'
= link_to 'Preguntas', admin_preguntas_path, :title => "Administrar listado de preguntas", :class => 'button'
= link_to 'Reiniciar Evento.', reset_admin_evento_path(@evento), :confirm => "Esta seguro?", :class => 'button negative'
= link_to 'Siguiente Pregunta >>.', siguiente_pregunta_admin_dashboard_path, :class => 'button positive'
= link_to 'Siguiente Candidato >>', siguiente_candidato_admin_dashboard_path,:class => 'button positive'
%hr

%h2 Cambiar estado de Evento
.mantform
  = semantic_form_for @evento, :url => admin_evento_path(@evento) do |form|
    = form.inputs do
      = form.input :estado, :as => :select, :collection => [['Inactivo', 0], ['Activo', 1], ['Finalizado', 2]]
    = buttons_update(admin_eventos_path)

%h2 Cambiar Pregunta Actual
.mantform
  = semantic_form_for @evento, :url => admin_evento_path(@evento) do |form|
    = form.inputs do
      = form.input :pregunta, :as => :select, :collection => @preguntas
    = buttons_update(admin_eventos_path)

%h2 Cambiar Candidato Actual
.mantform
  = semantic_form_for @evento, :url => admin_evento_path(@evento) do |form|
    = form.inputs do
      = form.input :candidato, :as => :select, :collection => @candidatos
    = buttons_update(admin_eventos_path)

%h2 Agregar nueva pregunta
.mantform
  = semantic_form_for @pregunta, :url => admin_preguntas_path do |form|
    = form.inputs do
      = form.input :texto, :as => :text
    = buttons_update(admin_eventos_path)      