config/routes.rb
Eforo::Application.routes.draw do

  get "home/index"
  post "home/votar"
  get "home/estado"
  get "home/pregunta"
  get "home/estadisticas"
  get "home/acercade"
  get "home/licenciamiento"

  namespace :admin do
    resources :candidatos do
      member do
        get 'reorder'
      end
    end
    resources :eventos do
      member do
        get 'reset'
      end
    end
    resources :preguntas
    resource :dashboard do
      collection do
        get 'siguiente_pregunta'
        get 'siguiente_candidato'
      end
    end
  end

  match 'dashboard' => "admin/dashboard#show", :as => :dashboard
  match 'estadisticas' => "home#estadisticas", :as => :estadisticas
  match 'acercade' => "home#acercade", :as => :acercade
  match 'licenciamiento' => "home#licenciamiento", :as => :licenciamiento

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  caches_page :acerca_de
  caches_page :licenciamiento
  caches_action :index
  caches_action :estadisticas

  def index
    @login = Time.now.to_i

    @preguntas = Pregunta.all
    @candidatos = Candidato.all(:order => "codigo")

    @voto = Voto.new(:candidato => 0,
                     :pregunta => 0,
                     :puntaje => nil)
  end

  def votar
    params[:voto][:created_at] = Time.now
    params[:voto][:segundo] = Time.now.to_i

    @voto = Voto.create(params[:voto])

    @promedio = Promedio.last
    @promedio.votar(@voto.puntaje)

    json_response = {:promedio => @promedio.valor}

    respond_to do |wants|
      wants.json { render :json => json_response.to_json }
    end
  end

  def estado
    evento = Evento.last
    promedio = Promedio.last

    json_response = {:estado => evento.estado,
      :pregunta => evento.pregunta,
      :candidato => evento.candidato,
      :promedio => promedio.valor,
      :usuario => Time.now.to_i}

    logger.debug { "Estado #{json_response}" }

    respond_to do |wants|
      wants.json {  render :json => json_response.to_json }
    end
  end

  def pregunta
    pregunta = Pregunta.find(params[:pregunta_id])
    json_response = {:id => pregunta.id,
      :orden => pregunta.orden,
      :texto => pregunta.texto}

    logger.debug { "Pregunta #{json_response}" }
    
    respond_to do |wants|
      wants.json {  render :json => json_response.to_json }
    end
  end

  def estadisticas
    @promedios = PromedioCandidato.all(:order => "pregunta, candidato")
  end

  def acercade
  end

  def licencimiento
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_candidato.html.haml
#candidato-actual.span-15.last.shadow
  .title.span-15.last
    %h3  Candidato en uso de la palabra
  %hr.space
  #candidato
    #candidato-bio.span-14.prepend-1.last
      - @candidatos.each do |candidato|
        %div{:id => candidato.id, :class => 'candidato'}
          %div.span-7
            = image_tag(candidato.imagen, :title => candidato.partido + ' - ' + candidato.nombre, :size => "260x260")
          %div.span-7.last
            %table
              %tr
                %th Nombre:
                %td= candidato.nombre
              %tr
                %th Partido:
                %td= candidato.partido
              %tr
                %th Web:
                %td= link_to candidato.url
    #candidato-califica.span-14.prepend-1.last
      %div.span-7
        #voto
          ¿Como respondio?
          = form_for(@voto, :url => '/home/votar.json', :remote => true) do |f|
            = f.hidden_field('candidato')
            = f.hidden_field('pregunta')
            = f.select('puntaje', options_for_select([["5. Excelente", 5], ["4. Buena", 4], ["3. Regular", 3], ["2. Mala", 2], ["1. Pésima", 1] ]), {:prompt => 'Califícala..'})
            %br
            = submit_tag 'Enviar Calificación', :id => "submit_vote"
        #gracias.success
          Gracias por tu voto. Por favor espera la siguiente pregunta.
      #estadistica.span-6.last
        %h2 Punteo
        #estadistica-grafica
          %h3#promedio 0.00
    %hr.space
  #no-hay-candidato
    No hay candidato en uso de la palabra

app/views/home/_estados.html.haml
#evento-no-iniciado.span-15.last.rounded.shadow
  %h2 Foro Virtual 2011
  %h3 Evento por iniciar
  %p Gracias por participar en el Foro Virtual 2011.
  %p Espera unos momentos mientras inicia el evento.
#evento-finalizado.span-15.last.rounded.shadow
  %h2 Foro Virtual 2011
  %h3 Evento ha Concluido
  %p Gracias por haber participado.
  %p Visita la pagina de Estadisticas para ver los resultados    
#evento-cargando.span-15.last.rounded.shadow
  %h2 Foro Virtual 2011
  %h3 Cargando...

app/views/home/_header.html.haml
#header.span-24.last
  #logo.span-9.prepend-1
    %h1
      \#EForo
      %span 2011
    %p.slogan Un esfuerzo personal en apoyo a @EstoesGuate.
  #navigation.span-14.last
    = link_to 'Inicio', root_path
    = link_to 'Estadisticas', estadisticas_path
    = link_to 'Acerca de', acercade_path
    = link_to 'Licenciamiento', licenciamiento_path
%hr.space

app/views/home/_pregunta.html.haml
#pregunta-actual.span-15.last.shadow.rounded
  %ol#preguntas
    - @preguntas.each do |pregunta|
      %li{:id => pregunta.id.to_s, :class => "pregunta" }
        = pregunta.to_label
  %span#no-hay-pregunta
    No se ha realizado una pregunta...

app/views/home/_twitter_button.html.erb
<a href="http://twitter.com/share" class="twitter-share-button" data-text="#eForo" data-count="vertical" data-via="EstoesGuate" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

app/views/home/_twitter_feed.html.erb
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'search',
  search: '#eforo',
  interval: 6000,
  title: 'Foro Virtual 2011',
  subject: '#eForo',
  width: 250,
  height: 350,
  theme: {
    shell: {
      background: '#8ec1da',
      color: '#ffffff'
    },
    tweets: {
      background: '#ffffff',
      color: '#444444',
      links: '#1985b5'
    }
  },
  features: {
    scrollbar: false,
    loop: true,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    toptweets: true,
    behavior: 'default'
  }
}).render().start();
</script>

app/views/home/acercade.html.haml
= render 'header'
#acercade.span-22.prepend-1.append-1.last
  %h2 Acerca de la aplicación
  %p "Tomando como base el ejemplo de #{link_to '@EstoesGuate', 'http://twitter.com/estoesguate'} , y el éxito del primer #{link_to 'Foro Virtual para candidatos a la alcaldía metropolitana', 'http://www.facebook.com/event.php?eid=108949322537691'} de la ciudad de Guatemala de La Asunción, tome la desición de poner mi granito de arena."
  %p La idea detras de esta aplicación es simple. Actualmente podemos 'medir' la aprobación a las respuesta dadas por los candidatos de cualquier foro leyendo los comentarios en las redes sociales. Sin embargo no hay una manera estandar de poner esa información en números, los cuales nos permitan determinar un 'ganador' del evento.
  %p ¿Por qué es importante esto?
  %p Porque los póliticos sueles responder en base a la frase 'Si no puedes contra ellos, confundelos...'. Lo cual esta bien, si nuestro objetivo es escuchar información inutil. Sin embargo si nuestra intención es poder medir las mejores respuestas a la problematica presentada, necesitamos datos concretos sobre las repuestas de los candidatos.
  %p Así pues deja a su disposición está aplicación para ser usada para futuros eventos, esperando que esta inciativa ayude a unirnos como hermanos y a tomar la mejor desición para el futuro de nuestro país.
  %br
  %p= link_to '@JmanGt', 'http://twitter.com/jmangt'

app/views/home/estadisticas.html.haml
= render 'header'
#main.span-22.prepend-1.append-1.last
  %h1 Estadisticas

  %table
    %thead
      %tr
        %th Pregunta
        %th Candidato
        %th Votos Recibidos
        %th Excelente
        %th Buena
        %th Regular
        %th Mala      
        %th Pésima
        %th Promedio
        %th Punteo
        %tbody
          - for promedio in @promedios do
            %tr
              %td= promedio.pregunta.orden
              %td= promedio.candidato.nombre
              %td= promedio.n
              %td= promedio.votos[4]
              %td= promedio.votos[3]
              %td= promedio.votos[2]
              %td= promedio.votos[1]
              %td= promedio.votos[0]
              %td= promedio.valor.round(3)
              %td= ((promedio.valor * 100)/5).round(3)

app/views/home/index.html.haml
= content_for :footer do
  = javascript_include_tag 'homepage.js'
= render 'header'
#main.span-22.prepend-1.append-1.last
  #content.span-15
    = render 'pregunta'
    %hr.space
    = render 'candidato'    
    %hr.space
    = render 'estados'
  #sidebar.span-7.last
    #logo.span-7.last
      = link_to image_tag('esto-es-guate-logo.jpg', :title => "EstoEsGuate"), 'https://twitter.com/#!/EstoesGuate'
    #feeds.span-7.last
    = render 'twitter_button'
    = render 'twitter_feed'
%hr.space
= hidden_field_tag 'estado_evento', ''
= hidden_field_tag 'pregunta_actual', ''
= hidden_field_tag 'candidato_actual', ''
= hidden_field_tag 'promedio_actual', ''
= hidden_field_tag 'usuario_actual', ''

app/views/home/licenciamiento.html.haml
= render 'header'
#licenciamiento.span-22.prepend-1.append-1.last
  %h2 Licenciamiento
  %p Copyright (c) 2011 JManGt
  %p Se autoriza, de forma gratuita, a cualquier persona que ha obtenido una copia de este software y archivos asociados de documentación (el "Software"), para tratar en el Software sin restricción, incluyendo sin ninguna limitación en lo que concierne los derechos para usar, copiar, modificar, fusionar, publicar, distribuir, sublicenciar, y / o vender copias de este Software, y para permitir a las personas que usan el Software para hacerlo, con sujeción a las siguientes condiciones:
  %p El aviso de copyright anterior y este aviso de permiso se incluirá en todas las copias o partes sustanciales de este Software.
  %p EL SOFTWARE SE ENTREGA "TAL CUAL", SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O IMPLÍCITA, no limitado a la GARANTÍAS DE COMERCIALIZACIÓN, CAPACIDAD DE HACER Y DE NO INFRACCIÓN DE COPYRIGHT. EN NINGÚN CASO LOS AUTORES O TITULARES DEL COPYRIGHT SERÁN RESPONSABLES DE NINGUNA RECLAMACIÓN, DAÑOS U OTRAS RESPONSABILIDADES, YA SEA EN UN LITIGIO, AGRAVIO O DE OTRO MODO, DERIVADAS DE, FUERA DE O EN CONEXION CON EL SOFTWARE SU UTILIZACIÓN U OTRAS OPERACIONES EN EL SOFTWARE.
  %hr
  %h3 Código Fuente
  %p El código fuente de esta apliación esta disponible para uso, copia, modificación y distribucioń en GitHub.com.
  %p= link_to 'IR A CODIGO FUENTE', 'https://github.com/jalvarezsamayoa/EForoGt'